FROM itzg/minecraft-server
LABEL MAINTAINER Angel Alvarado "angel.angelio@gmail.com"
USER root
COPY ./start-deployBukkitSpigot /start-deployBukkitSpigot
RUN chmod +x /start-deployBukkitSpigot
COPY ./start-minecraftFinalSetup /start-minecraftFinalSetup
RUN chmod +x /start-minecraftFinalSetup

